export const AUTH_SIGN_IN_START = "AUTH_SIGN_IN_START";
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const AUTH_FORGOT_PASSWORD_START = "AUTH_FORGOT_PASSWORD_START";
export const AUTH_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD";
